services:
  backend:
    volumes:
      - ./app:/usr/src/app
  
  database:
    ports:
      - 5432:5432

  redis-insight:
    image: redis/redisinsight:latest
    ports:
      - 5540:5540
    volumes:
      - redisinsight:/data

  rq-dashboard:
    image: eoranged/rq-dashboard
    ports:
      - 9181:9181
    environment:
      - RQ_DASHBOARD_REDIS_URL=redis://nexus-iq-redis-1:6379/0
    depends_on:
      - redis

  pgadmin:
    depends_on:
      database:
        condition: service_started
    image: dpage/pgadmin4
    ports:
      - 8001:80
    volumes:
      - pgadmindata:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ja.bladt@gmail.com
      PGADMIN_DEFAULT_PASSWORD: geheim2

volumes:
  pgadmindata:
  redisinsight:
