services:
  backend:
    command: [
      "uv", "run",
      "-m", "debugpy", "--listen", "0.0.0.0:5678",
      "-m", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload", "--reload-dir", "/usr/src/app"
    ]
    develop:
      watch:
        - action: sync
          path: ./app
          target: /usr/src/app
          ignore:
            - .venv/
        - action: rebuild
          path: ./pyproject.toml
    environment:
      SKIP_DDRAGON_CHOWN: "1"
    ports:
      - 8000:8000
      - 5678:5678
    volumes:
      - ./app:/usr/src/app
      - ./ddragon:/usr/src/ddragon
  
  database:
    ports:
      - 5432:5432

  redis-insight:
    image: redis/redisinsight:latest
    ports:
      - 5540:5540
    volumes:
      - redisinsight:/data

  rq-dashboard:
    image: cjlapao/rq-dashboard:latest
    ports:
      - 9181:9181
    environment:
      - RQ_DASHBOARD_REDIS_URL=redis://nexus-iq-redis-1:6379/0
    depends_on:
      - redis

volumes:
  redisinsight:
