services:
  backend:
    build:
      context: .
    env_file: ".env"
    image: nexus-iq/backend
    ports:
      - 8000:8000
    volumes:
      - ./ddragon:/usr/src/ddragon:ro
    environment:
      DDragon_CACHE_DIR: /usr/src/ddragon/cdn


  database:
    image: postgres:18-alpine
    environment:
      POSTGRES_PASSWORD: geheim2
      POSTGRES_DB: nexus_iq
    volumes:
      - pgdata:/var/lib/postgresql/data

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage

volumes:
  pgdata:
  qdrant_storage:
